### PR TITLE
[MOHGP] try_split robustness against linalg error

### PR DESCRIPTION
**Pull request by mzwiessele**
- Added linalg error catch clauses, preventing linalg errors to fail optimization
- some adjustments to plotting with new GPy

### CODE REVIEW

**Comment by jameshensman** [comment]
Do you think we should at least print a warning if we catch a LinAlgError?

**Comment by mzwiessele** [comment]
Usually the linalg errors occur at convergence, as the covariance matrix goes non singular. Therefore, it is not a real error, it is just that the numerics haven't caught up to the convergence yet. So, IMHO I do not think it is worth telling the user that. 

Up to you, though : )

**Comment by jameshensman** [comment]
Yes please, and also add your name to contributors at the bottom of the
readme file.

James.

**Comment by mzwiessele** [comment]
I've added the warning in on the second fail, when the direct gradient step is taken.

**Pull request merged**
